"""add missing indexes, fks, and ondelete behavior

Revision ID: 076a76032e89
Revises: 181ea66c4f40
Create Date: 2026-06-22 06:35:14.985340

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076a76032e89'
down_revision: Union[str, None] = '181ea66c4f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, then hand-edited to give the new/recreated FK
    # constraints explicit deterministic names (Base.metadata has no naming_convention, so
    # autogenerate emitted unnamed `create_foreign_key(None, ...)` calls whose matching
    # `drop_constraint(None, ...)` in downgrade() would fail against a real Postgres backend) ###
    # No geometry columns are added/altered here, so no new GiST indexes are needed - those are
    # created implicitly by GeoAlchemy2's DDL event listeners at table-creation time, not via
    # op.create_index() in a migration.
    op.create_foreign_key('alerts_property_id_fkey', 'alerts', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_county_risk_scores_county_fips'), 'county_risk_scores', ['county_fips'], unique=False)
    op.create_index(op.f('ix_flood_zones_fips'), 'flood_zones', ['fips'], unique=False)
    op.create_index(op.f('ix_gis_features_layer_version_id'), 'gis_features', ['layer_version_id'], unique=False)
    op.drop_constraint(op.f('gis_features_layer_version_id_fkey'), 'gis_features', type_='foreignkey')
    op.create_foreign_key('gis_features_layer_version_id_fkey', 'gis_features', 'layer_versions', ['layer_version_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_layer_versions_layer_id'), 'layer_versions', ['layer_id'], unique=False)
    op.drop_constraint(op.f('layer_versions_layer_id_fkey'), 'layer_versions', type_='foreignkey')
    op.create_foreign_key('layer_versions_layer_id_fkey', 'layer_versions', 'map_layers', ['layer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_procurement_opportunities_county_fips'), 'procurement_opportunities', ['county_fips'], unique=False)
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=False)
    op.create_index(op.f('ix_property_risk_scores_property_id'), 'property_risk_scores', ['property_id'], unique=False)
    op.drop_constraint(op.f('property_risk_scores_property_id_fkey'), 'property_risk_scores', type_='foreignkey')
    op.create_foreign_key('property_risk_scores_property_id_fkey', 'property_risk_scores', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_score_explanations_county_fips'), 'score_explanations', ['county_fips'], unique=False)
    op.create_index(op.f('ix_score_explanations_property_id'), 'score_explanations', ['property_id'], unique=False)
    op.drop_constraint(op.f('score_explanations_property_id_fkey'), 'score_explanations', type_='foreignkey')
    op.create_foreign_key('score_explanations_property_id_fkey', 'score_explanations', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_source_runs_source_id'), 'source_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_runs_started_at'), 'source_runs', ['started_at'], unique=False)
    op.drop_constraint(op.f('source_runs_source_id_fkey'), 'source_runs', type_='foreignkey')
    op.create_foreign_key('source_runs_source_id_fkey', 'source_runs', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('subscriptions_property_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_property_id_fkey', 'subscriptions', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_water_observations_station_parameter_observed', 'water_observations', ['station_id', 'parameter', 'observed_at'])
    op.drop_constraint(op.f('water_observations_station_id_fkey'), 'water_observations', type_='foreignkey')
    op.create_foreign_key('water_observations_station_id_fkey', 'water_observations', 'water_stations', ['station_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_water_stations_county_fips', 'water_stations', ['county_fips'], unique=False)
    op.create_index(op.f('ix_water_stations_source_id'), 'water_stations', ['source_id'], unique=False)
    op.create_unique_constraint('uq_water_stations_source_external', 'water_stations', ['source_id', 'external_id'])
    op.create_index(op.f('ix_weather_alerts_is_active'), 'weather_alerts', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_alerts_is_active'), table_name='weather_alerts')
    op.drop_constraint('uq_water_stations_source_external', 'water_stations', type_='unique')
    op.drop_index(op.f('ix_water_stations_source_id'), table_name='water_stations')
    op.drop_index('ix_water_stations_county_fips', table_name='water_stations')
    op.drop_constraint('water_observations_station_id_fkey', 'water_observations', type_='foreignkey')
    op.create_foreign_key(op.f('water_observations_station_id_fkey'), 'water_observations', 'water_stations', ['station_id'], ['id'])
    op.drop_constraint('uq_water_observations_station_parameter_observed', 'water_observations', type_='unique')
    op.drop_constraint('subscriptions_property_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_property_id_fkey'), 'subscriptions', 'properties', ['property_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_constraint('source_runs_source_id_fkey', 'source_runs', type_='foreignkey')
    op.create_foreign_key(op.f('source_runs_source_id_fkey'), 'source_runs', 'sources', ['source_id'], ['id'])
    op.drop_index(op.f('ix_source_runs_started_at'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_source_id'), table_name='source_runs')
    op.drop_constraint('score_explanations_property_id_fkey', 'score_explanations', type_='foreignkey')
    op.create_foreign_key(op.f('score_explanations_property_id_fkey'), 'score_explanations', 'properties', ['property_id'], ['id'])
    op.drop_index(op.f('ix_score_explanations_property_id'), table_name='score_explanations')
    op.drop_index(op.f('ix_score_explanations_county_fips'), table_name='score_explanations')
    op.drop_constraint('property_risk_scores_property_id_fkey', 'property_risk_scores', type_='foreignkey')
    op.create_foreign_key(op.f('property_risk_scores_property_id_fkey'), 'property_risk_scores', 'properties', ['property_id'], ['id'])
    op.drop_index(op.f('ix_property_risk_scores_property_id'), table_name='property_risk_scores')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_index(op.f('ix_procurement_opportunities_county_fips'), table_name='procurement_opportunities')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_constraint('layer_versions_layer_id_fkey', 'layer_versions', type_='foreignkey')
    op.create_foreign_key(op.f('layer_versions_layer_id_fkey'), 'layer_versions', 'map_layers', ['layer_id'], ['id'])
    op.drop_index(op.f('ix_layer_versions_layer_id'), table_name='layer_versions')
    op.drop_constraint('gis_features_layer_version_id_fkey', 'gis_features', type_='foreignkey')
    op.create_foreign_key(op.f('gis_features_layer_version_id_fkey'), 'gis_features', 'layer_versions', ['layer_version_id'], ['id'])
    op.drop_index(op.f('ix_gis_features_layer_version_id'), table_name='gis_features')
    op.drop_index(op.f('ix_flood_zones_fips'), table_name='flood_zones')
    op.drop_index(op.f('ix_county_risk_scores_county_fips'), table_name='county_risk_scores')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_constraint('alerts_property_id_fkey', 'alerts', type_='foreignkey')
    # ### end Alembic commands ###
